@startuml
!include style.puml
skinparam componentStyle rectangle
skinparam Component {
    FontColor #FFFFFF
    FontSize 15
    BorderThickness 1
    BorderColor #FFFFFF
    FontName Arial
}

package "PingBook" <<Rectangle>> {
    component Main #808080
    component UI UI_COLOR
    component Logic LOGIC_COLOR
    component Model MODEL_COLOR
    component Storage STORAGE_COLOR
    component Commons LOGIC_COLOR_T2
}

actor User as User USER_COLOR

User --> UI
Main --> UI
Main --> Logic
Main --> Model
Main --> Storage

UI --> Logic
UI --> Model
Logic --> Model
Logic --> Storage
Storage --> Model

UI ..> Commons
Logic ..> Commons
Model ..> Commons
Storage ..> Commons
@enduml
