@startuml
!include style.puml
skinparam ArrowFontStyle plain

Actor User as user USER_COLOR
Participant ":UI" as ui UI_COLOR
Participant ":Logic" as logic LOGIC_COLOR
Participant ":Model" as model MODEL_COLOR
Participant ":Storage" as storage STORAGE_COLOR

user -[USER_COLOR]> ui : enter command
activate ui UI_COLOR

ui -[UI_COLOR]> logic : execute command
activate logic LOGIC_COLOR

logic -[LOGIC_COLOR]> model : update contact data
activate model MODEL_COLOR

model -[MODEL_COLOR]-> logic
deactivate model

logic -[LOGIC_COLOR]> storage : persist updated data
activate storage STORAGE_COLOR

storage --[STORAGE_COLOR]> logic
deactivate storage

logic --[LOGIC_COLOR]> ui : return result
deactivate logic

ui --[UI_COLOR]> user : show result
deactivate ui
@enduml
